### ISSUE TITLE
[TASK] Fix Calendar Functionality

### ISSUE THREAD

**Issue by khantaaseen** [WSU-4110/CRM-Web-Application#106]
### Title

Calendar CRUD operations

### Description

Ensure the calendar component displays events properly.

### Acceptance criteria

- Calendar displays all events input by the user
- Users can add, edit, and delete calendar events without error
- Calendar sidebar showcases upcoming events with date and title.

### Estimate

2

### Associated feature

#104 #21 #5 #10

**Comment by AmmarAhmed1735** [comment]
Taaseen Completed this and the calendar page is now integrated and is its own page
