### ISSUE TITLE
[TASK] Setup User Auth

### ISSUE THREAD

**Issue by khantaaseen** [WSU-4110/CRM-Web-Application#107]
### Title

Implement User Authentication and Authorization

### Description

 Configure and test user authentication methods.

### Acceptance criteria

- Users should be allowed to register
- Returning users can log in and log out
- Users can register as a business with required information
- Only registered users can access pages

### Estimate

<2

### Associated feature

#10 #102 #12 #13

**Comment by AmmarAhmed1735** [comment]
I completed this and also includes oauth now.
