### ISSUE TITLE
[TASK] Send Email Integration

### ISSUE THREAD

**Issue by khantaaseen** [WSU-4110/CRM-Web-Application#108]
### Title

Send email to customer from business dashboard

### Description

A business owner can send an email to customers from the customers page.

### Acceptance criteria

- Email sends from business owner email
- Email sends to selected customer
- Form on displays subject and email content box

### Estimate

1

### Associated feature

#102 #20 #67 #7

**Comment by AmmarAhmed1735** [comment]
Taaseen completed and added this to the customers page
